<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonSave</name>
   <tag></tag>
   <elementGuidId>b91919c7-2c9a-4834-a010-d21c0a75ac02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;root&quot;]/main/div/div[2]/div/div[2]/div[2]/div/form/div/div[2]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;root&quot;]/main/div/div[2]/div/div[2]/div[2]/div/form/div/div[2]/button</value>
   </webElementProperties>
</WebElementEntity>
