<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>menuPulsa</name>
   <tag></tag>
   <elementGuidId>77bc5cbe-7906-49e3-8319-948ad8d7d324</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;root&quot;]/main/div/div/a[3]/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;root&quot;]/main/div/div/a[3]/div/span</value>
      <webElementGuid>5ba22d1e-6199-4099-86ce-278b8bef7743</webElementGuid>
   </webElementProperties>
</WebElementEntity>
