<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>informasiAkun</name>
   <tag></tag>
   <elementGuidId>f47b808a-3df3-4e43-85f0-16c8ae52f0a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;root&quot;]/main/div/div[2]/div/div[1]/div/div/div[3]/div[1]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;root&quot;]/main/div/div[2]/div/div[1]/div/div/div[3]/div[1]/a</value>
   </webElementProperties>
</WebElementEntity>
