<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>keterangan</name>
   <tag></tag>
   <elementGuidId>50aed1d2-37df-40d7-939f-10e989c5b682</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;root&quot;]/main/div[2]/div/div/div[2]/div/table/thead/tr/th[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;root&quot;]/main/div[2]/div/div/div[2]/div/table/thead/tr/th[1]</value>
   </webElementProperties>
</WebElementEntity>
