<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>saldopoint</name>
   <tag></tag>
   <elementGuidId>fa401222-691d-4c71-8aa4-04c61a38ed5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;root&quot;]/main/div[2]/div/div/div[2]/div/table/thead/tr/th[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;root&quot;]/main/div[2]/div/div/div[2]/div/table/thead/tr/th[4]</value>
   </webElementProperties>
</WebElementEntity>
