<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonOK</name>
   <tag></tag>
   <elementGuidId>2072d6a7-7ca1-49e8-81ea-9ab15f1ed5b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[2]/div/div[6]/button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[2]/div/div[6]/button[1]</value>
      <webElementGuid>1365dc5b-5548-4f4b-b386-3562e102f3d3</webElementGuid>
   </webElementProperties>
</WebElementEntity>
