<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cashOut</name>
   <tag></tag>
   <elementGuidId>fad8c332-18fd-4625-abf3-7106767e77c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;root&quot;]/main/div[2]/div/div[2]/form/div[2]/div/a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;root&quot;]/main/div[2]/div/div[2]/form/div[2]/div/a[1]</value>
   </webElementProperties>
</WebElementEntity>
