<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>redeemPointMenu</name>
   <tag></tag>
   <elementGuidId>f3284173-12cc-40ee-9854-400bea41a098</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;root&quot;]/main/div/div[2]/div/div[1]/div/div/div[3]/div[5]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;root&quot;]/main/div/div[2]/div/div[1]/div/div/div[3]/div[5]/a/span</value>
   </webElementProperties>
</WebElementEntity>
