<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>settingAccount</name>
   <tag></tag>
   <elementGuidId>68066bad-1ce5-40be-90d0-b14d49f6e948</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;root&quot;]/main/div/div[2]/div/div[1]/div/div/div[3]/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;root&quot;]/main/div/div[2]/div/div[1]/div/div/div[3]/div[2]/a</value>
   </webElementProperties>
</WebElementEntity>
