<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonHapus</name>
   <tag></tag>
   <elementGuidId>311c5276-0de1-4a1e-801b-5d07ebdc9f47</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;root&quot;]/main/div/section[3]/div/table/tbody/tr[10]/td[3]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;root&quot;]/main/div/section[3]/div/table/tbody/tr[10]/td[3]/button</value>
   </webElementProperties>
</WebElementEntity>
