<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>customer</name>
   <tag></tag>
   <elementGuidId>e1d393a8-d165-40d2-9640-64975192801b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;navbarSupportedContent&quot;]/ul[1]/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;navbarSupportedContent&quot;]/ul[1]/li[2]/a</value>
   </webElementProperties>
</WebElementEntity>
